### ISSUE TITLE
no longer compile on linux

### ISSUE THREAD

**Issue by lichtl** [DarkstarProject/darkstar#1805]
no longer compile on Ubuntu 14.04

g++ -std=c++1y -DHAVE_CONFIG_H -I. -I./src/common      -DdsUDPSERV   -I/usr//include/luajit-2.0   -I/usr/include/mysql -DBIG_JOINS=1  -fno-strict-aliasing    -g -DNDEBUG  -g -O2 -MT dsgame-ai_general.o -MD -MP -MF .deps/dsgame-ai_general.Tpo -c -o dsgame-ai_general.o `test -f 'src/map/ai/ai_general.cpp' || echo './'`src/map/ai/ai_general.cpp
src/map/ai/ai_general.cpp: In member function ‘void CAIGeneral::SetCurrentSpell(uint16)’:
src/map/ai/ai_general.cpp:289:28: error: ‘make_unique’ is not a member of ‘std’
                 m_PSpell = std::make_unique<CBlueSpell>(*static_cast<CBlueSpell*>(spell));
                            ^
src/map/ai/ai_general.cpp:289:55: error: expected primary-expression before ‘>’ token
                 m_PSpell = std::make_unique<CBlueSpell>(*static_cast<CBlueSpell*>(spell));
                                                       ^
src/map/ai/ai_general.cpp:293:28: error: ‘make_unique’ is not a member of ‘std’
                 m_PSpell = std::make_unique<CSpell>(*spell);
                            ^
src/map/ai/ai_general.cpp:293:51: error: expected primary-expression before ‘>’ token
                 m_PSpell = std::make_unique<CSpell>(*spell);
                                                   ^
make: *** [dsgame-ai_general.o] Error 1
ubuntu@ip-172-31-9-17:~/t/darkstar$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by teschnei** [comment]
search issues before posting:
https://github.com/DarkstarProject/darkstar/issues/1777
